In [3]:
import seaborn as sns
import pandas as pd 
df=sns.load_dataset('tips')

In [4]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

encoded_data=encoder.fit_transform(df['time'])

In [14]:
encoded_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [15]:
from sklearn.preprocessing import LabelEncoder
encoder_time=LabelEncoder()

encoded_data=encoder_time.fit_transform(df['time'])

In [17]:
print('classes',encoder_time.classes_)

classes ['Dinner' 'Lunch']

In [23]:
encoded_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [21]:
for number, category in enumerate(encoder_time.classes_):
    print(category, "-------", number)

Dinner ------- 0
Lunch ------- 1

In [25]:
encoder_day=LabelEncoder()

encoded_day_data=encoder.fit_transform(df['day'])

In [34]:
print('classes',encoder_day_data.classes_)

NameError: name 'encoder_day_data' is not defined

In [35]:
for category, number in zip(encoder_day.classes_, range(len(encoder_day.classes_))):
    print(category, "-----", number)

AttributeError: 'LabelEncoder' object has no attribute 'classes_'

In [30]:
for category ,number in zip(encoder_day.classes_,range(len(encoder_day.classes_))):
    print(category,"-----",number)

AttributeError: 'LabelEncoder' object has no attribute 'classes_'

In [36]:
encoder_day.inverse_transform(0,1,2,3)

TypeError: LabelEncoder.inverse_transform() takes 2 positional arguments but 5 were given

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [38]:
ohe=OneHotEncoder(sparse_output=False)

In [40]:
ohe=OneHotEncoder(sparse_output=False,drop='first')

In [41]:
ohe_encoder=ohe.fit_transform(df[['sex','smoker']])

In [43]:
ohe.fit_transform(df[['sex','smoker']])

df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())

In [44]:
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

In [39]:
ohe.fit_transform(df[['sex','smoker']])

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.]])

In [45]:
from sklearn.preprocessing import FunctionTransformer

In [46]:
import numpy as np

In [51]:
power=FunctionTransformer(np.log10)
power.fit_transform(df['tip'])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [ ]:
power=FunctionTransformer(np.log10)
power.fit_transform(df['tip'])

In [59]:
from sklearn.preprocessing import PowerTransformer
import numpy as np

In [63]:
X=np.array([
    [-1],
    [0],
    [3],
    [5],
    [10],
    [50],
])

In [64]:
pt=PowerTransformer(method="yeo-johnson")

In [80]:
X_transformed=pt.fit_transform(X)

In [81]:
print("Original:")
print(X.ravel())

Original:
[-1  0  3  5 10 50]

In [82]:
print("\nTransformed:")
print(np.round(X_transformed.ravel(),3))
print("\nLearned lambda:")
print(pt.lambdas_)

Transformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

Learned lambda:
[0.09126797]

In [86]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

# Right-skewed feature (2D array shaped 5x1)
y = np.array([[1], [2], [3], [10], [50]])

# Method must be "box-cox" with a hyphen (-)
pt = PowerTransformer(method="box-cox")
y_transformed = pt.fit_transform(y)

print('Original:')
print(y.ravel())

print('\nTransformed:')
print(np.round(y_transformed.ravel(), 3))

print('\nLearned lambda:')
print(pt.lambdas_)

Original:
[ 1  2  3 10 50]

Transformed:
[-1.37  -0.6   -0.216  0.689  1.497]

Learned lambda:
[-0.29064466]

In [87]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [88]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry'],
    # Numerical features with NaN
    'Age': [25, np.nan, 30, 35, np.nan, 40, 28, 32],
    'Salary': [50000, 60000, np.nan, 80000, 55000, np.nan, 62000, 75000],
    # Categorical features with NaN
    'City': ['New York', 'London', np.nan, 'Paris', 'London', 'New York', np.nan, 'Paris'],
    'Department': ['HR', 'IT', 'IT', np.nan, 'Sales', 'HR', 'Sales', np.nan],
    # Target / Feature
    'Experience_Years': [2, 5, 7, 10, 3, 12, np.nan, 8]
}

df = pd.DataFrame(data)
df

      Name   Age   Salary      City Department  Experience_Years
0    Alice  25.0  50000.0  New York         HR               2.0
1      Bob   NaN  60000.0    London         IT               5.0
2  Charlie  30.0      NaN       NaN         IT               7.0
3    David  35.0  80000.0     Paris        NaN              10.0
4      Eva   NaN  55000.0    London      Sales               3.0
5    Frank  40.0      NaN  New York         HR              12.0
6    Grace  28.0  62000.0       NaN      Sales               NaN
7    Henry  32.0  75000.0     Paris        NaN               8.0

In [90]:
from sklearn.impute import SimpleImputer

In [92]:
imputer=SimpleImputer(strategy='mean')
imputer.fit_transform(df[['Salary']])

array([[50000.        ],
       [60000.        ],
       [63666.66666667],
       [80000.        ],
       [55000.        ],
       [63666.66666667],
       [62000.        ],
       [75000.        ]])

In [93]:
imputer=SimpleImputer(strategy='mean')
imputer.fit_transform(df[['Salary']]).flatten()

array([50000.        , 60000.        , 63666.66666667, 80000.        ,
       55000.        , 63666.66666667, 62000.        , 75000.        ])

In [96]:
imputer=SimpleImputer(strategy='mean')

df['new_salary']=imputer.fit_transform(df[['Salary']]).flatten()

In [97]:
df

      Name   Age   Salary      City Department  Experience_Years    new_salary
0    Alice  25.0  50000.0  New York         HR               2.0  50000.000000
1      Bob   NaN  60000.0    London         IT               5.0  60000.000000
2  Charlie  30.0      NaN       NaN         IT               7.0  63666.666667
3    David  35.0  80000.0     Paris        NaN              10.0  80000.000000
4      Eva   NaN  55000.0    London      Sales               3.0  55000.000000
5    Frank  40.0      NaN  New York         HR              12.0  63666.666667
6    Grace  28.0  62000.0       NaN      Sales               NaN  62000.000000
7    Henry  32.0  75000.0     Paris        NaN               8.0  75000.000000

In [98]:
imputer=SimpleImputer(strategy='median')
imputer.fit_transform(df[['Salary']]).flatten()

array([50000., 60000., 61000., 80000., 55000., 61000., 62000., 75000.])

In [101]:
imputer=SimpleImputer(strategy='median')

df['new_Experience_Years']=imputer.fit_transform(df[['Experience_Years']]).flatten()

In [102]:
df

,Name,Age,Salary,City,Department,Experience_Years,new_salary,new_Experience_Years
0,Alice,25.0,50000.0,New York,HR,2.0,50000.0,2.0
1,Bob,NaN,60000.0,London,IT,5.0,60000.0,5.0
2,Charlie,30.0,NaN,NaN,IT,7.0,61000.0,7.0
3,David,35.0,80000.0,Paris,NaN,10.0,80000.0,10.0
4,Eva,NaN,55000.0,London,Sales,3.0,55000.0,3.0
5,Frank,40.0,NaN,New York,HR,12.0,61000.0,12.0
6,Grace,28.0,62000.0,NaN,Sales,NaN,62000.0,7.0
7,Henry,32.0,75000.0,Paris,NaN,8.0,75000.0,8.0

In [105]:
imputer=SimpleImputer(strategy='most_frequent')

df['new_Department']=imputer.fit_transform(df[['Department']]).flatten()

In [106]:
df

,Name,Age,Salary,City,Department,Experience_Years,new_salary,new_Experience_Years,new_Department
0,Alice,25.0,50000.0,New York,HR,2.0,50000.0,2.0,HR
1,Bob,NaN,60000.0,London,IT,5.0,60000.0,5.0,IT
2,Charlie,30.0,NaN,NaN,IT,7.0,61000.0,7.0,IT
3,David,35.0,80000.0,Paris,NaN,10.0,80000.0,10.0,HR
4,Eva,NaN,55000.0,London,Sales,3.0,55000.0,3.0,Sales
5,Frank,40.0,NaN,New York,HR,12.0,61000.0,12.0,HR
6,Grace,28.0,62000.0,NaN,Sales,NaN,62000.0,7.0,Sales
7,Henry,32.0,75000.0,Paris,NaN,8.0,75000.0,8.0,HR